POST http://localhost:8000/business/confirm-order/do
Content-Type: application/json
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYmYiOjE2OTA1NDAwMDcsIm1vYmlsZSI6IjEzODAwMTM4MDAwIiwiaWQiOjE2Nzg0MjU5MzA5MTk0NDg1NzYsImV4cCI6MTY5MDYyNjQwNywiaWF0IjoxNjkwNTQwMDA3fQ.o8b5B1XTziPOORabMRgcs0j8XXfO0Yn8D7EXLmx4qZg

{
  "dailyTrainTicketId": 1685184298375843840,
  "date": 1690560000000,
  "end": "郑州",
  "start": "广州",
  "tickets": [
    {
      "passengerId": 1685168370137305088,
      "passengerIdCard": "550",
      "passengerName": "李四",
      "passengerType": "2",
      "seatTypeCode": "2"
    }
  ],
  "trainCode": "D1"
}

###

GET http://localhost:8000/business/confirm-order/query-line-count/1662452972099080192
Content-Type: application/json
token: {{token}}
