POST http://localhost:8000/business/confirm-order/do
Content-Type: application/json
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYmYiOjE2OTU1MjYxNzIsIm1vYmlsZSI6IjEzODAwMTM4MDAwIiwiaWQiOjE2ODUxNTYzODA1OTc2ODYyNzIsImV4cCI6MTY5NTYxMjU3MiwiaWF0IjoxNjk1NTI2MTcyfQ.9sJJdno6WmNIVqvU0GSKk0UuSiBVT2oJD5IBpI6WZFg

{
  "dailyTrainTicketId": 1705417777168388096,
  "date": 1696435200000,
  "end": "武汉",
  "imageCode": "bfwn",
  "imageCodeToken": "Oqpwdgkv",
  "lineNumber": 0,
  "start": "广州",
  "tickets": [
    {
      "passengerId": 1685168370137305088,
      "passengerIdCard": "550",
      "passengerName": "李四",
      "passengerType": "2",
      "seatTypeCode": "2"
    }
  ],
  "trainCode": "D1"
}

###

GET http://localhost:8000/business/confirm-order/query-line-count/1662452972099080192
Content-Type: application/json
token: {{token}}
