POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "name": "test",
  "idCard": "123321",
  "type": "1"
}
###

GET http://localhost:8000/member/passenger/query-list?page=1&size=3
Accept: application/json
token: {{token}}

###

POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "id": 1681622887833931776,
  "memberId": 1678425930919448576,
  "name": "test-test",
  "idCard": "123321",
  "type": "1"
}
###

DELETE http://localhost:8000/member/passenger/delete/1681681711093649408
Content-Type: application/json
token: {{token}}

###